name: Docker Build & Publish
 
on:
  push:
    branches:
      - master
 
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
 
      - name: Create .env file
        run: |
            echo "API_URL=${{ secrets.API_URL }}" >> .env
            echo "MAPBOX_TOKEN=${{ secrets.MAPBOX_TOKEN }}" >> .env
            echo ".env file created with API_URL and MAPBOX_TOKEN"
 
      - name: Login to Docker Hub
        run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
 
      - name: Build Docker Image
        run: docker build -t pipeanayap/nature-app:${{ github.sha }} .
 
      - name: Tag Latest
        run: docker tag pipeanayap/nature-app:${{ github.sha }} pipeanayap/nature-app:latest
 
      - name: Push Docker Image
        run: |
          docker push pipeanayap/nature-app:${{ github.sha }}
          docker push pipeanayap/nature-app:latest
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to AWS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker system prune -af --volumes
            df -h
            docker pull pipeanayap/nature-app:latest
            cd containers
            docker compose down
            docker compose up -d --force-recreate